### ISSUE TITLE
[Fabric 1.19.2] Crash on Start with Datapacks

### ISSUE THREAD

**Issue by suerion** [MehVahdJukaar/Moonlight#100]
Hey, our Server does not finsih loading anymore, after updating moonlight....

[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/11239133/latest.log)

With -> moonlight-1.19.2-2.2.29-fabric - works without problems

```[12:32:20] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.ClassCastException: class java.util.concurrent.ConcurrentLinkedDeque cannot be cast to class java.util.List (java.util.concurrent.ConcurrentLinkedDeque and java.util.List are in module java.base of loader 'bootstrap')
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:194) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.19-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.ClassCastException: class java.util.concurrent.ConcurrentLinkedDeque cannot be cast to class java.util.List (java.util.concurrent.ConcurrentLinkedDeque and java.util.List are in module java.base of loader 'bootstrap')
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:25) ~[moonlight-1.19.2-2.2.30-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.19.2-2.2.30-fabric.jar:?]
	at net.minecraft.class_6861.handler$fph000$moonlight$dynamicPackEarlyReload(class_6861.java:1034) ~[server-intermediary.jar:?]
	at net.minecraft.class_6861.<init>(class_6861.java:60) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237$class_7238.method_42099(class_7237.java:61) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_6904.method_40431(class_6904.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:158) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:952) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:946) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:156) ~[server-intermediary.jar:?]
	... 5 more

**Comment by suerion** [comment]
Fixed with latest Update ;) @MehVahdJukaar thanks for your work
