### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by B10Reaper** [MehVahdJukaar/Moonlight#12]
I've added Selene, Supplementaries and Skinned Lanterns along with the mods I'd been using beforehand. Everything was fine, then maybe 2 or 3 days later it suddenly started hard crashing with this same error. As of the error Forge and Java were both up to date as far as I could see. I tried deleting the entities file altogether and reloading, tried an earlier backup, rolled back the java version installed, fresh install of the server, a computer restart between each step and eventually had to remove the mods 1 by 1 to figure out which was causing it. This is the last crash report before I got it running by removing the mods.

`---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2021-10-27, 10:04 p.m.
Description: Exception ticking world

java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[fmlloader-1.17.1-37.0.103.jar%2322!:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-0.9.54.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at net.minecraft.world.level.saveddata.maps.MapItemSavedData.handler$zzc000$getUpdatePacket(SourceFile:814) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:mixin,re:classloading,pl:mixin:APP:selene.mixins.json:MapDataMixin,pl:mixin:A}
	at net.minecraft.world.level.saveddata.maps.MapItemSavedData.m_164796_(SourceFile:421) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:mixin,re:classloading,pl:mixin:APP:selene.mixins.json:MapDataMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerEntity.m_8533_(ServerEntity.java:89) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading}
	at net.minecraft.server.level.ChunkMap.m_140421_(ChunkMap.java:994) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:364) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:347) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:334) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:818) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:683) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[fmlloader-1.17.1-37.0.103.jar%2322!:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-0.9.54.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at net.minecraft.world.level.saveddata.maps.MapItemSavedData.handler$zzc000$getUpdatePacket(SourceFile:814) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:mixin,re:classloading,pl:mixin:APP:selene.mixins.json:MapDataMixin,pl:mixin:A}
	at net.minecraft.world.level.saveddata.maps.MapItemSavedData.m_164796_(SourceFile:421) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:mixin,re:classloading,pl:mixin:APP:selene.mixins.json:MapDataMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerEntity.m_8533_(ServerEntity.java:89) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading}
	at net.minecraft.server.level.ChunkMap.m_140421_(ChunkMap.java:994) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:364) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:347) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['B10Reaper'/669, l='ServerLevel[Brimbleton]', x=-1591.75, y=103.35, z=-1138.50]]
	Chunk stats: 3862
	Level dimension: minecraft:overworld
	Level spawn location: World: (-1276,71,-936), Section: (at 4,7,8 in -80,4,-59; chunk contains blocks -1280,0,-944 to -1265,255,-929), Region: (-3,-2; contains chunks -96,-64 to -65,-33, blocks -1536,0,-1024 to -1025,255,-513)
	Level time: 11335902 game time, 2657979 day time
	Level name: 
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 41154 (now: false), thunder time: 57631 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:334) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:818) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:683) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 9177554072 bytes (8752 MiB) / 10737418240 bytes (10240 MiB) up to 16106127360 bytes (15360 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz
	Identifier: Intel64 Family 6 Model 26 Stepping 5
	Microarchitecture: Nehalem (Server)
	Frequency (GHz): 2.67
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9649
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.07
	Memory slot #0 type: Other
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.07
	Memory slot #1 type: Other
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.07
	Memory slot #2 type: Other
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.07
	Memory slot #3 type: Other
	Memory slot #4 capacity (MB): 2048.00
	Memory slot #4 clockSpeed (GHz): 1.07
	Memory slot #4 type: Other
	Memory slot #5 capacity (MB): 2048.00
	Memory slot #5 clockSpeed (GHz): 1.07
	Memory slot #5 type: Other
	Virtual memory max (MB): 81911.11
	Virtual memory used (MB): 42563.62
	Swap memory total (MB): 61440.00
	Swap memory used (MB): 156.04
	JVM Flags: 2 total; -Xmx15G -Xms10G
	Player Count: 1 / 5; [ServerPlayer['(Redacted), l='ServerLevel[Redacted]', x=-1591.75, y=103.35, z=-1138.50]]
	Data Packs: vanilla, mod:configured (incompatible), mod:thevanillaexperience, mod:buildersaddition (incompatible), mod:snowundertrees, mod:worldedit (incompatible), mod:biomesoplenty, mod:cfm, mod:catalogue (incompatible), mod:extendedcreativeinventory, mod:cloth_config (incompatible), mod:forge, mod:bambooeverything (incompatible), mod:goldenhopper, mod:collective, mod:configurableextramobdrops, mod:craftingautomat (incompatible), mod:the_wild_update, mod:dynview (incompatible), mod:restored_earth, mod:absentbydesign (incompatible), mod:citadel (incompatible), mod:alexsmobs (incompatible), mod:additionallanterns, mod:skinnedlanterns (incompatible), mod:supermartijn642corelib (incompatible), mod:supplementaries (incompatible), mod:selene (incompatible), mod:mcwlights (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		server-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: NOSIGNATURE
		The_Wild_Update_Mod_V0.5_Minecraft_1.17.1.jar     |The Wild Update 1.19 Mod      |the_wild_update               |0.5                 |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.17.1-14.0.0.36-universal.jar      |Biomes O' Plenty              |biomesoplenty                 |1.17.1-14.0.0.36    |DONE      |Manifest: NOSIGNATURE
		CraftingAutomat-MC1.17.1-1.2.2.jar                |Crafting Automat              |craftingautomat               |1.2.2               |DONE      |Manifest: NOSIGNATURE
		additionallanterns-1.0.0a-mc1.17.jar              |Additional Lanterns           |additionallanterns            |1.0.0a              |DONE      |Manifest: NOSIGNATURE
		skinned_lanterns-1.17.1-1.3.1.jar                 |Skinned Lanterns              |skinnedlanterns               |1.17.1-1.3.1        |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.12-mc1.17.jar          |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.12              |DONE      |Manifest: NOSIGNATURE
		bambooeverything-1.1.1-build.4+mc1.17.1.jar       |Bamboo Everything             |bambooeverything              |1.1.1-build.4+mc1.17|DONE      |Manifest: NOSIGNATURE
		goldenhopper-1.2.4-1.17.1.jar                     |Golden Hopper                 |goldenhopper                  |1.2.4               |DONE      |Manifest: NOSIGNATURE
		1collective-1.17.1-2.64.jar                       |Collective                    |collective                    |2.64                |DONE      |Manifest: NOSIGNATURE
		configurableextramobdrops_1.17.1-1.6.jar          |Configurable Extra Mob Drops  |configurableextramobdrops     |1.6                 |DONE      |Manifest: NOSIGNATURE
		citadel-1.9.3-1.17.1.jar                          |Citadel                       |citadel                       |1.9.3               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.13.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.13.1              |DONE      |Manifest: NOSIGNATURE
		configured-1.2.0-1.17.1.jar                       |Configured                    |configured                    |1.2.0               |DONE      |Manifest: NOSIGNATURE
		thevanillaexperience_1.17.1-1.4.jar               |The Vanilla Experience        |thevanillaexperience          |1.4                 |DONE      |Manifest: NOSIGNATURE
		buildersaddition-1.17.1-20210823a.jar             |Builders Crafts & Addition    |buildersaddition              |1.17.1-20210823a    |DONE      |Manifest: NOSIGNATURE
		snowundertrees-1.17.1-1.1.5.jar                   |Snow Under Trees              |snowundertrees                |1.1.5               |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.6.jar                           |WorldEdit                     |worldedit                     |7.2.6+4b2d1e7       |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0pre25-1.17.1.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre25         |DONE      |Manifest: NOSIGNATURE
		catalogue-1.3.0-1.17.1.jar                        |Catalogue                     |catalogue                     |1.3.0               |DONE      |Manifest: NOSIGNATURE
		extendedcreativeinventory_1.17.1-1.6.jar          |Extended Creative Inventory   |extendedcreativeinventory     |1.6                 |DONE      |Manifest: NOSIGNATURE
		dynviewdist-2.2.jar                               |Dynamic view distance         |dynview                       |1.8                 |DONE      |Manifest: NOSIGNATURE
		restored_earth-1.17.1-1.1.0.jar                   |Restored Earth                |restored_earth                |1.1.0               |DONE      |Manifest: NOSIGNATURE
		cloth-config-5.0.38-forge.jar                     |Cloth Config v4 API           |cloth_config                  |5.0.38              |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.0.103-universal.jar               |Forge                         |forge                         |37.0.103            |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		absentbydesign-1.17.1-1.6.0.jar                   |Absent By Design Mod          |absentbydesign                |1.17.1-1.6.0        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		supplementaries-1.17.1-0.18.0a.jar                |Supplementaries               |supplementaries               |1.17.1-0.18.0       |DONE      |Manifest: NOSIGNATURE
		selene-1.17.1-1.9.0.jar                           |Selene                        |selene                        |1.17.1-1.1          |DONE      |Manifest: NOSIGNATURE
		mcw-lights-1.0.1-mc1.17.1.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.1               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 963c9cc4-0643-4243-858d-7e9999fc885e
	FML: 37.0
	Forge: net.minecraftforge:37.0.103`

**Comment by Xelbayria** [comment]
is the issue resolved?

**Comment by MehVahdJukaar** [comment]
yeah that definitly was fixed
