### ISSUE TITLE
crash after finishing generating spawn

### ISSUE THREAD

**Issue by Sinogard** [MehVahdJukaar/Moonlight#127]
````
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-08-16 20:37:37
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Cannot add empty stack
	at net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroupEntries.checkStack(FabricItemGroupEntries.java:501)
	at net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroupEntries.checkStacks(FabricItemGroupEntries.java:495)
	at net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroupEntries.addAfter(FabricItemGroupEntries.java:417)
	at net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroupEntries.addAfter(FabricItemGroupEntries.java:257)
	at net.mehvahdjukaar.moonlight.api.platform.fabric.RegHelperImpl.lambda$addItemsToTabsRegistration$12(RegHelperImpl.java:220)
	at net.fabricmc.fabric.impl.itemgroup.ItemGroupEventsImpl.lambda$createModifyEvent$1(ItemGroupEventsImpl.java:46)
	at net.minecraft.class_1761.handler$bjh000$fabric-item-group-api-v1$getStacks(class_1761.java:1077)
	at net.minecraft.class_1761.method_47306(class_1761.java:107)
	at net.minecraft.class_1761.polymer$getContentsWith(class_1761.java:2544)
	at eu.pb4.polymer.core.api.item.PolymerItemGroupUtils.getContentsFor(PolymerItemGroupUtils.java:37)
	at eu.pb4.universalshops.gui.setup.SelectItemGui.updateCachedItems(SelectItemGui.java:109)
	at eu.pb4.universalshops.UniversalShopsMod.lambda$onInitialize$0(UniversalShopsMod.java:38)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$bjl000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:3842)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.4, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 729341128 bytes (695 MiB) / 1971322880 bytes (1880 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 32
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5950X 16-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 4080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2704
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3667
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 32768.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 32768.00
	Memory slot #3 clockSpeed (GHz): 2.67
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 150448.69
	Virtual memory used (MB): 35877.99
	Swap memory total (MB): 19456.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx8G
	Fabric Mods: 
		additionalentityattributes: Additional Entity Attributes 1.4.0+1.20.0
		alloy_forgery: Alloy Forgery 2.0.22+1.20
		allthetrims: AllTheTrims 3.2.3
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		almostunified: AlmostUnified 1.20.1-0.6.0
		archeologyplus: Archeology Plus 1.0.1
		architectury: Architectury 9.1.12
		argonauts: Argonauts 1.0.2
			placeholder-api: Placeholder API 2.1.1+1.20
		ash_api: Ash API 3.0.2+1.20.1
		athena: Athena 3.0.1
		balm-fabric: Balm 7.0.7
		bclib: BCLib 3.0.13
			wunderlib: WunderLib 1.1.5
		beaconoverhaul: Beacon Overhaul 1.8.2+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		bee_info: More Bee info  1.1.2
		bettercombat: Better Combat 1.7.3+1.20.1
		betterend: Better End 4.0.10
		betternether: Better Nether 9.0.9
		bigextras: BigExtras 1.9.2+1.20.1
			playerabilitylib: Pal 1.8.0
		blockus: Blockus 2.7.5+1.20.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		brewinandchewin: Brewin And Chewin fabric-2.1.5+1.20.1
			mm: Manningham Mills 2.3
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.98
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.98
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.98
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.98
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.98
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.98
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.98
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.98
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.98
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.98
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.98
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.98
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.98
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.98
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.98
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.98
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.98
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.98
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.98
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.98
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		chipped: Chipped 3.0.1
		chunky: Chunky 1.3.92
		cinderscapes: Cinderscapes 4.0.8
			biolith: Biolith 1.0.0-alpha.8
			cinderscapes-common: Cinderscapes: Common 4.0.8
			cinderscapes-worldgen: Cinderscapes: World Generation 4.0.8
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 7.0.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.1
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		clutter: Clutter 1.20-0.4.1
		combatroll: Combat Roll 1.2.1+1.20.1
		conjuring: Conjuring 1.0.28+1.20
			lavender: Lavender 0.1.0-pre.6+1.20
				lavender-md: lavender-md 0.1.0-pre.3+1.20
				lavender-md-owo-ui: lavender-md-owo-ui 0.1.0-pre.3+1.20
		culturaldelights: Cultural Delights Fabric 0.14.11+1.20.1
		cupboard: cupboard 1.20.1-1.5
		customizableelytra: Customizable Elytra 2.1.0+1.20
		digs_dnd_origins: Digs DnD Origins 1.20.1-0.0.11
		distractingtrims: DistractingTrims 2.0.2
		dungeon_difficulty: Dungeon Difficulty 2.0.5+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		easymagic: Easy Magic 8.0.1
		easyshulkerboxes: Easy Shulker Boxes 8.0.0
			puzzlesapi: Puzzles Api 8.0.2
				puzzlesaccessapi: Puzzles Access Api 8.0.5
		emi: EMI 1.0.19+1.20.1+fabric
		enhancedgroups: Simple Voice Chat Enhanced Groups 1.20.1-1.4.0
		expandeddelight: Expanded Delight 0.3.0.2
		expandedstorage: Expanded Storage 10.0.0-beta.3
		fabric-api: Fabric API 0.86.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.1+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+4df89eb277
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-hammers: Fabric Hammers 1.0.0
		fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.22
		fallingtree: FallingTree 4.3.0
		farmersdelight: Farmer's Delight 1.20.1-1.4.1
		farsight: Farsight Mod 1.20.1-4.1
			org_jctools_jctools-core: jctools-core 4.0.1
		ferritecore: FerriteCore 6.0.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		frycmobvariants: Mob Variants 4.2.2+1.20
		gazebo: Gazebos 1.0.1+1.20.1
		geckolib: Geckolib 4.2.1
			com_eliotlash_mclib_mclib: mclib 20
		grapplemod: Grappling Hook Mod 1.20-v1.7
		handcrafted: Handcrafted 3.0.1
		iceberg: Iceberg 1.1.14
		java: OpenJDK 64-Bit Server VM 17
		knavesneeds: Knaves' Needs 1.1.5.1+1.20.1
		lithium: Lithium 0.11.2
		milkevsessentials: Milkevs Essentials 1.9.2b
		minecraft: Minecraft 1.20.1
		miniextras: Mini Extras 1.8.1+1.20.1
		mod-loading-screen: Mod Loading Screen 1.0.2
			com_formdev_flatlaf: flatlaf 3.0
			net_lenni0451_reflect: Reflect 1.0.2
		moonlight: Moonlight 1.20-2.8.3
		morediscs: More Music Discs 1.20.1-28-fabric
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v2.1.4
		mr_edf_remastered: Ender Dragon Fight Remastered 4.3
		myloot: myLoot 4.0.3-1.20.1
			omega-config: OmegaConfig 1.2.3-1.18.1
		mythicmetals: Mythic Metals 0.18.2+1.20
			common-protection-api: Common Protection API 1.0.0
		mythicmetals_decorations: Mythic Metals Decorations 0.5.5+1.20
		no_more_purple: No More Purple 1.2.1
		noexpensive: NoExpensive 1.20.1-1.9.0
		openpartiesandclaims: Open Parties and Claims 0.19.3
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				calio: Calio 1.11.0
		origins-classes: Origins: Classes 1.7.0
		origins-plus-plus: Origins++ 2.1.1
		owo: oωo 0.11.1+1.20
			blue_endless_jankson: jankson 1.2.2
		pehkui: Pehkui 3.7.8+1.14.4-1.20.1
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		player-animator: Player Animator 1.0.2-rc1+1.20
		plushables: Plushables 1.1.1
			midnightlib: MidnightLib 1.4.1
		polymorph: Polymorph 0.49.0+1.20.1
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-block: Cardinal Components API (blocks) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			cardinal-components-item: Cardinal Components API (items) 5.2.1
			spectrelib: SpectreLib 0.13.13+1.20.1
		profundis: Profundis 1.6.0
		projectile_damage: Projectile Damage Attribute 3.2.2+1.20.1
		prometheus: Prometheus 1.0.2
		puzzleslib: Puzzles Lib 8.0.19
		reinfshulker: Reinforced Shulker Boxes 2.4.1+1.20
			reinfcore: Reinforced Core 3.1.2+1.20
		resourcefullib: Resourceful Lib 2.1.9
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		retraining: Retraining 1.3.0
		ruined_equipment: Ruined Equipment 2.3.1
		runes: Runes 0.9.10+1.20.1
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		simplyswords: Simply Swords 1.50.0-1.20.1
		slotswap: Slot Swap 1.1.0+mc1.20.1
		snifferplus: Hellion's Sniffer+ 0.2.0
		spell_engine: Spell Engine 0.9.28+1.20.1
		spell_power: Spell Power Attribute 0.9.14+1.20.1
		spoornpacks: SpoornPacks 5.0-1.20.1
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.1
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.1
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.1
		stackable: Stackable 1.1.0
		starlight: Starlight 1.1.2+fabric.dbc156f
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.7
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.12+b
		supplementaries: Supplementaries 1.20-2.5.26
		suppsquared: Supplementaries Squared 1.20-1.1.8
		tectonic: Tectonic 2.1
		terrablender: TerraBlender 3.0.0.169
		things: Things 0.3.1+1.20
		timecontrol: TimeControl 1.4.1
		tradingpost: Trading Post 8.0.1
		trinkets: Trinkets 3.7.1
		ubesdelight: Ube's Delight 0.1.3-p1
		universal_shops: Universal Shops 1.3.2+1.20.1
			common-economy-api: Common Economy API 1.1.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			polymer-core: Polymer (Core) 0.5.3+1.20.1
				polymer-networking: Polymer (Networking) 0.5.3+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.3+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.3+1.20.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.3+1.20.1
				polymer-common: Polymer (Common) 0.5.3+1.20.1
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
			sgui: sgui 1.2.2+1.20
		usefulbackpacks: Useful Backpacks 2.0.1.121
		uteamcore: U Team Core 5.1.3.267
		vanityslots: Vanity Slots 1.2.9
		vcinteraction: Voice Chat Interaction 1.20.1-1.0.3
		voicechat: Simple Voice Chat 1.20.1-2.4.20
		waystones: Waystones 14.0.1
		wizards: Wizards 0.9.19+1.20.1
		wwoo: William Wythers' Overhauled Overworld 3.2.0-beta
		xaerominimap: Xaero's Minimap 23.6.2
		xaeroworldmap: Xaero's World Map 1.33.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.0+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, fabric, tectonic:tectonic, milkevsessentials:milkevscustomrules, milkevsessentials:rottenfleshtoleather, milkevsessentials:toolbelt, milkevsessentials:extendo_grips, Supplementaries Generated Pack, Suppsquared Generated Pack, spoornpacks
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)`
```

**Comment by Xelbayria** [comment]
Try the latest version and check to see if the issue still persists.
