### ISSUE TITLE
Moonlight hanging sign extension crash when using Ad Astra mod

### ISSUE THREAD

**Issue by MetaForge** [MehVahdJukaar/Moonlight#133]
[Render thread/WARN]: Failed to generate hanging sign extension texture for ad_astra:aeronos. Could be that the target mod isnt registering their wood type properly
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4730.method_24147()" because the return value of "net.minecraft.class_4722.method_45781(net.minecraft.class_4719)" is null
	at net.mehvahdjukaar.supplementaries.dynamicpack.ClientDynamicResourcesGenerator.regenerateDynamicAssets(ClientDynamicResourcesGenerator.java:239) ~[supplementaries-1.20-2.5.28-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.reloadResources(DynResourceGenerator.java:115) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.onEarlyReload(DynResourceGenerator.java:84) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.lambda$postEvent$1(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.minecraft.class_6861.handler$egm000$moonlight$dynamicPackEarlyReload(class_6861.java:2534) ~[client-intermediary.jar:?]
	at net.minecraft.class_6861.<init>(class_6861.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_3304.method_18232(class_3304.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_36561(class_310.java:950) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1521(class_310.java:928) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5385(class_1255.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1513(class_310.java:2469) ~[client-intermediary.jar:?]
	at net.minecraft.class_1066.method_4642(class_1066.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18096(class_310.java:2191) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18099(class_310.java:2158) ~[client-intermediary.jar:?]
	at net.minecraft.class_433.method_47632(class_433.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_7574.method_46552(class_7574.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_433.method_19836(class_433.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1241) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.14.22-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
[22:56:16] [Render thread/WARN]: Failed to generate hanging sign extension texture for ad_astra:strophar. Could be that the target mod isnt registering their wood type properly
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4730.method_24147()" because the return value of "net.minecraft.class_4722.method_45781(net.minecraft.class_4719)" is null
	at net.mehvahdjukaar.supplementaries.dynamicpack.ClientDynamicResourcesGenerator.regenerateDynamicAssets(ClientDynamicResourcesGenerator.java:239) ~[supplementaries-1.20-2.5.28-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.reloadResources(DynResourceGenerator.java:115) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.onEarlyReload(DynResourceGenerator.java:84) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.lambda$postEvent$1(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.minecraft.class_6861.handler$egm000$moonlight$dynamicPackEarlyReload(class_6861.java:2534) ~[client-intermediary.jar:?]
	at net.minecraft.class_6861.<init>(class_6861.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_3304.method_18232(class_3304.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_36561(class_310.java:950) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1521(class_310.java:928) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5385(class_1255.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1513(class_310.java:2469) ~[client-intermediary.jar:?]
	at net.minecraft.class_1066.method_4642(class_1066.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18096(class_310.java:2191) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18099(class_310.java:2158) ~[client-intermediary.jar:?]
	at net.minecraft.class_433.method_47632(class_433.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_7574.method_46552(class_7574.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_433.method_19836(class_433.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1241) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.14.22-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
[22:56:16] [Render thread/WARN]: Failed to generate hanging sign extension texture for ad_astra:glacian. Could be that the target mod isnt registering their wood type properly
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4730.method_24147()" because the return value of "net.minecraft.class_4722.method_45781(net.minecraft.class_4719)" is null
	at net.mehvahdjukaar.supplementaries.dynamicpack.ClientDynamicResourcesGenerator.regenerateDynamicAssets(ClientDynamicResourcesGenerator.java:239) ~[supplementaries-1.20-2.5.28-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.reloadResources(DynResourceGenerator.java:115) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.onEarlyReload(DynResourceGenerator.java:84) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.lambda$postEvent$1(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.minecraft.class_6861.handler$egm000$moonlight$dynamicPackEarlyReload(class_6861.java:2534) ~[client-intermediary.jar:?]
	at net.minecraft.class_6861.<init>(class_6861.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_3304.method_18232(class_3304.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_36561(class_310.java:950) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1521(class_310.java:928) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5385(class_1255.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1513(class_310.java:2469) ~[client-intermediary.jar:?]
	at net.minecraft.class_1066.method_4642(class_1066.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18096(class_310.java:2191) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18099(class_310.java:2158) ~[client-intermediary.jar:?]
	at net.minecraft.class_433.method_47632(class_433.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_7574.method_46552(class_7574.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_433.method_19836(class_433.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1241) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.14.22-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
[22:56:16] [Render thread/WARN]: Failed to generate hanging sign extension texture for betterarcheology:rotten. Could be that the target mod isnt registering their wood type properly
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4730.method_24147()" because the return value of "net.minecraft.class_4722.method_45781(net.minecraft.class_4719)" is null
	at net.mehvahdjukaar.supplementaries.dynamicpack.ClientDynamicResourcesGenerator.regenerateDynamicAssets(ClientDynamicResourcesGenerator.java:239) ~[supplementaries-1.20-2.5.28-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.reloadResources(DynResourceGenerator.java:115) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.onEarlyReload(DynResourceGenerator.java:84) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.lambda$postEvent$1(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.minecraft.class_6861.handler$egm000$moonlight$dynamicPackEarlyReload(class_6861.java:2534) ~[client-intermediary.jar:?]
	at net.minecraft.class_6861.<init>(class_6861.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_3304.method_18232(class_3304.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_36561(class_310.java:950) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1521(class_310.java:928) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5385(class_1255.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1513(class_310.java:2469) ~[client-intermediary.jar:?]
	at net.minecraft.class_1066.method_4642(class_1066.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18096(class_310.java:2191) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18099(class_310.java:2158) ~[client-intermediary.jar:?]
	at net.minecraft.class_433.method_47632(class_433.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_7574.method_46552(class_7574.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_433.method_19836(class_433.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1241) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.14.22-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
[22:56:16] [Render thread/WARN]: Failed to generate hanging sign extension texture for canvas sign, 
java.io.IOException: java.util.NoSuchElementException: No value present
	at net.mehvahdjukaar.moonlight.api.resources.textures.SpriteUtils.readImage(SpriteUtils.java:30) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.textures.TextureImage.open(TextureImage.java:158) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.dynamicpack.ClientDynamicResourcesGenerator.regenerateDynamicAssets(ClientDynamicResourcesGenerator.java:253) ~[supplementaries-1.20-2.5.28-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.reloadResources(DynResourceGenerator.java:115) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.onEarlyReload(DynResourceGenerator.java:84) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.lambda$postEvent$1(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	at net.minecraft.class_6861.handler$egm000$moonlight$dynamicPackEarlyReload(class_6861.java:2534) ~[client-intermediary.jar:?]
	at net.minecraft.class_6861.<init>(class_6861.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_3304.method_18232(class_3304.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_36561(class_310.java:950) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1521(class_310.java:928) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5385(class_1255.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1513(class_310.java:2469) ~[client-intermediary.jar:?]
	at net.minecraft.class_1066.method_4642(class_1066.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18096(class_310.java:2191) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18099(class_310.java:2158) ~[client-intermediary.jar:?]
	at net.minecraft.class_433.method_47632(class_433.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_7574.method_46552(class_7574.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_433.method_19836(class_433.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1241) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.14.22-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.resources.textures.SpriteUtils.readImage(SpriteUtils.java:27) ~[moonlight-1.20-2.8.9-fabric.jar:?]
	... 43 more

**Comment by MehVahdJukaar** [comment]
If you are crashing that's not the reason. That's just a warn for a mod that added a wood type and didn't add their stuff to vanilla wood maps. Send a latest.log and don't paste part of it here, always send the full file

**Comment by MetaForge** [comment]
Keeps crashing the server while trying to pre-generate the world with chunky passed 4096 blocks, and sporadically crashed a client twice while just running around near the spawn area (while no chunk generation was occurring as the world is already pre-grenerated up to 4096 blocks).

Full log : https://gist.github.com/MetaForge/1f10abbdada4fb67ad5fb9537f7a11a3

**Comment by MehVahdJukaar** [comment]
So log ends without any error, doesn't look like it's crashing from it. All stuff that is WARN will never cause s crash, only ERROR ones could but even then it's not guaranteed and infsct I see no actual crash error on the log so I don't know. If it crashed just the client and not the server I obviously need to see the client log

**Comment by MetaForge** [comment]
Client log is long gone sorry, but if it happens again ill send that one through

**Comment by Xelbayria** [comment]
Alright you can close this issue. if it comes back again, then u can create a new issue.  make sure you are using the latest version to check if the issue still persists. Confirm that Moonlight is the culprit. Good day!

**Comment by ehx-v1** [comment]
Also, pregen crashes and sporadic crashes sounds like a generic Out Of Memory problem. I don't think this is specific to Moonlight, even if it happens again. If it crashes with Moonlight and doesn't without, try removing a mod that needs Moonlight but keeping Moonlight itself in. Just looking through the dependent mods on CurseForge, some of them (such as Immersive Weathering) sound like they could go quite hard on the JVM memory.

**Comment by Xelbayria** [comment]
Oh ok. You'll need to make sure you have enough RAM allocated to Minecraft.  Usually, you'll need at least 4GB of RAM for a few to dozen: 4GB. A _mod pack_ requires a minimum of 6GB.
