### ISSUE TITLE
[Fabric 1.20.1] Rendersystem called from wrong thread

### ISSUE THREAD

**Issue by LZ1WS** [MehVahdJukaar/Moonlight#134]
It started crashing after Moonlight's 2.8.12 update
<details>
<summary>Details</summary>

```
[Netty Local Client IO #0/ERROR]: An error occurred while trying to generate dynamic assets for Moonlight Mods Dynamic Assets:
java.lang.IllegalStateException: Rendersystem called from wrong thread
at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:184) ~[client-intermediary.jar:?]
at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThreadOrInit(RenderSystem.java:168) ~[client-intermediary.jar:?]
at net.minecraft.class_1044.method_4624(class_1044.java:39) ~[client-intermediary.jar:?]
at net.minecraft.class_1043.<init>(class_1043.java:36) ~[client-intermediary.jar:?]
at net.mehvahdjukaar.supplementaries.client.GlobeManager$TextureInstance.<init>(GlobeManager.java:64) ~[supplementaries-1.20-2.5.28-fabric.jar:?]
at net.mehvahdjukaar.supplementaries.client.GlobeManager.lambda$getTextureInstance$0(GlobeManager.java:45) ~[supplementaries-1.20-2.5.28-fabric.jar:?]
at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:?]
at net.mehvahdjukaar.supplementaries.client.GlobeManager.getTextureInstance(GlobeManager.java:44) ~[supplementaries-1.20-2.5.28-fabric.jar:?]
at net.mehvahdjukaar.supplementaries.client.GlobeManager.refreshTextures(GlobeManager.java:35) ~[supplementaries-1.20-2.5.28-fabric.jar:?]
at net.mehvahdjukaar.supplementaries.client.GlobeManager.refreshColorsAndTextures(GlobeManager.java:132) ~[supplementaries-1.20-2.5.28-fabric.jar:?]
at net.mehvahdjukaar.supplementaries.dynamicpack.ClientDynamicResourcesGenerator.regenerateDynamicAssets(ClientDynamicResourcesGenerator.java:66) ~[supplementaries-1.20-2.5.28-fabric.jar:?]
at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.reloadResources(DynResourceGenerator.java:115) ~[moonlight-1.20-2.8.12-fabric.jar:?]
at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.onEarlyReload(DynResourceGenerator.java:84) ~[moonlight-1.20-2.8.12-fabric.jar:?]
at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.lambda$postEvent$1(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.8.12-fabric.jar:?]
at java.util.concurrent.ConcurrentLinkedDeque.forEach(Unknown Source) ~[?:?]
at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.8.12-fabric.jar:?]
at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.20-2.8.12-fabric.jar:?]
at net.minecraft.class_6861.handler$jho000$moonlight$dynamicPackEarlyReload(class_6861.java:3534) ~[client-intermediary.jar:?]
at net.minecraft.class_6861.<init>(class_6861.java:60) ~[client-intermediary.jar:?]
at net.minecraft.class_3304.method_18232(class_3304.java:46) ~[client-intermediary.jar:?]
at net.minecraft.class_310.method_36561(class_310.java:950) ~[client-intermediary.jar:?]
at net.minecraft.class_310.method_1521(class_310.java:928) ~[client-intermediary.jar:?]
at net.diamonddev.simpletrims.network.SendQuietReload.quietlyReload(SendQuietReload.java:24) ~[simpletrims-0.2.0.jar:?]
at net.diamonddev.simpletrims.network.SendQuietReload.lambda$registerReceiver$0(SendQuietReload.java:17) ~[simpletrims-0.2.0.jar:?]
at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:98) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-ef4b5386ab5020ff.jar:?]
at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:40) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-ef4b5386ab5020ff.jar:?]
at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-ef4b5386ab5020ff.jar:?]
at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:90) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-ef4b5386ab5020ff.jar:?]
at net.minecraft.class_634.handler$ekp000$fabric-networking-api-v1$handleCustomPayload(class_634.java:3268) ~[client-intermediary.jar:?]
at net.minecraft.class_634.method_11152(class_634.java) ~[client-intermediary.jar:?]
at net.minecraft.class_2658.method_11457(class_2658.java:60) ~[client-intermediary.jar:?]
at net.minecraft.class_2658.method_11054(class_2658.java:8) ~[client-intermediary.jar:?]
at net.minecraft.class_2535.method_10759(class_2535.java:175) ~[client-intermediary.jar:?]
at net.minecraft.class_2535.method_10770(class_2535.java:160) ~[client-intermediary.jar:?]
at net.minecraft.class_2535.channelRead0(class_2535.java:52) ~[client-intermediary.jar:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
```

</details>

**Comment by LZ1WS** [comment]
Nvm was caused by mod Simple Trims
