### ISSUE TITLE
[🐞]: [Render thread/ERROR]: Error from mod 'moonlight'

### ISSUE THREAD

**Issue by SpiritOTHawk** [MehVahdJukaar/Moonlight#164]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of this mods and it's dependencies

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

2.8.48

### Issue Detail

java.lang.NullPointerException: There cannot be no categories or fallback category!

### Log Attachment

[Render thread/ERROR]: Error from mod 'moonlight'
java.lang.NullPointerException: There cannot be no categories or fallback category!
        at me.shedaniel.clothconfig2.impl.ConfigBuilderImpl.build(ConfigBuilderImpl.java:231) ~[cloth-config-11.1.106-fabric.jar:?]
        at net.mehvahdjukaar.moonlight.api.integration.cloth_config.ClothConfigCompat.makeScreen(ClothConfigCompat.java:55) ~[moonlight-1.20-2.8.48-fabric.jar:?]
        at net.mehvahdjukaar.moonlight.api.platform.configs.fabric.FabricConfigSpec.makeScreen(FabricConfigSpec.java:130) ~[moonlight-1.20-2.8.48-fabric.jar:?]
        at net.mehvahdjukaar.moonlight.api.platform.configs.ConfigSpec.makeScreen(ConfigSpec.java:102) ~[moonlight-1.20-2.8.48-fabric.jar:?]
        at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:61) ~[modmenu-7.2.2.jar:?]
        at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:114) ~[modmenu-7.2.2.jar:?]
        at net.minecraft.class_437.method_25423(class_437.java:297) ~[client-intermediary.jar:?]
        at net.minecraft.class_310.method_1507(class_310.java:1080) ~[client-intermediary.jar:?]
        at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:15) ~[modmenu-7.2.2.jar:?]
        at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
        at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
        at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
        at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
        at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
        at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
        at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
        at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
        at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
        at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
        at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
        at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
        at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.2.jar:?]
        at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
        at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-intermediary.jar:?]
        at net.minecraft.class_1041.method_15998(class_1041.java:288) ~[client-intermediary.jar:?]
        at net.minecraft.class_310.method_1523(class_310.java:1241) ~[client-intermediary.jar:?]
        at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
        at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
        at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
        at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
        at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]

**Comment by Xelbayria** [comment]
you can drag the file here (i meant a file, not part of it) and it will get uploaded. A full log will help devs to find out what's going on.

**Comment by SpiritOTHawk** [comment]
[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/13055686/latest.log)
