### ISSUE TITLE
[🐞]: Game doesn't launch with moonlight lib

### ISSUE THREAD

**Issue by GitUser14975** [MehVahdJukaar/Moonlight#195]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

moonlight-1.20-2.10.1-fabric.jar

### Issue Detail

When I try to launch the game, it doesn't even start and immediately shows me a message in the launcher that says:
```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'moonlight'!
```
It launches normally when I disable Moonlight Lib. The game seems to crash even with just Fabric API, Moonlight Lib and MmmMmmMmmMmm (Target Dummy) mods alone.

### Log Attachment

[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/14378453/latest.log)
[crash-2024-02-22_20.18.47-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/14378455/crash-2024-02-22_20.18.47-client.txt)

**Comment by Daltaxy** [comment]
same thing on forge 1.20.1 
loads fine on moonlight-1.20-2.10.0

**Comment by suerion** [comment]
I had a big Modpack here, the Server Crashes also with the newest moonlight

moonlight-1.20-2.10.1

[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/14379824/latest.log)


```
[23:04:26] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'moonlight'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.6.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.6-launcher.1.0.0.jar:1.0.0]
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.mehvahdjukaar.moonlight.api.trades.ModItemListing
		at net.mehvahdjukaar.sawmill.CarpenterTrades.init(CarpenterTrades.java:28) ~[sawmill-1.20-1.3.4-fabric.jar:?]
		at net.mehvahdjukaar.sawmill.SawmillMod.init(SawmillMod.java:71) ~[sawmill-1.20-1.3.4-fabric.jar:?]
		at net.mehvahdjukaar.sawmill.fabric.SawmillFabric.onInitialize(SawmillFabric.java:15) ~[sawmill-1.20-1.3.4-fabric.jar:?]
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.6.jar:?]
		at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.6-launcher.1.0.0.jar:1.0.0]
	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "main"]
		at net.mehvahdjukaar.moonlight.api.trades.ModItemListing.<clinit>(ModItemListing.java:11) ~[moonlight-1.20-2.10.1-fabric.jar:?]
		at net.mehvahdjukaar.moonlight.api.trades.ItemListingRegistry.<init>(ItemListingRegistry.java:46) ~[moonlight-1.20-2.10.1-fabric.jar:?]
		at net.mehvahdjukaar.moonlight.api.trades.ItemListingRegistry.<clinit>(ItemListingRegistry.java:31) ~[moonlight-1.20-2.10.1-fabric.jar:?]
		at net.mehvahdjukaar.moonlight.core.Moonlight.commonInit(Moonlight.java:71) ~[moonlight-1.20-2.10.1-fabric.jar:?]
		at net.mehvahdjukaar.moonlight.fabric.MoonlightFabric.onInitialize(MoonlightFabric.java:36) ~[moonlight-1.20-2.10.1-fabric.jar:?]
		... 8 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.mehvahdjukaar.moonlight.api.trades.ModItemListing
		at net.mehvahdjukaar.supplementaries.common.entities.trades.ModVillagerTrades.init(ModVillagerTrades.java:18) ~[supplementaries-1.20-2.8.1-fabric.jar:?]
		at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:66) ~[supplementaries-1.20-2.8.1-fabric.jar:?]
		at net.mehvahdjukaar.supplementaries.fabric.SupplementariesFabric.onInitialize(SupplementariesFabric.java:16) ~[supplementaries-1.20-2.8.1-fabric.jar:?]
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.6.jar:?]
		at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.6-launcher.1.0.0.jar:1.0.0]
	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "main"]
		at net.mehvahdjukaar.moonlight.api.trades.ModItemListing.<clinit>(ModItemListing.java:11) ~[moonlight-1.20-2.10.1-fabric.jar:?]
		at net.mehvahdjukaar.moonlight.api.trades.ItemListingRegistry.<init>(ItemListingRegistry.java:46) ~[moonlight-1.20-2.10.1-fabric.jar:?]
		at net.mehvahdjukaar.moonlight.api.trades.ItemListingRegistry.<clinit>(ItemListingRegistry.java:31) ~[moonlight-1.20-2.10.1-fabric.jar:?]
		at net.mehvahdjukaar.moonlight.core.Moonlight.commonInit(Moonlight.java:71) ~[moonlight-1.20-2.10.1-fabric.jar:?]
		at net.mehvahdjukaar.moonlight.fabric.MoonlightFabric.onInitialize(MoonlightFabric.java:36) ~[moonlight-1.20-2.10.1-fabric.jar:?]
		... 8 more
Caused by: java.lang.ExceptionInInitializerError
	at net.mehvahdjukaar.moonlight.api.trades.ItemListingRegistry.<init>(ItemListingRegistry.java:46) ~[moonlight-1.20-2.10.1-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.trades.ItemListingRegistry.<clinit>(ItemListingRegistry.java:31) ~[moonlight-1.20-2.10.1-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.core.Moonlight.commonInit(Moonlight.java:71) ~[moonlight-1.20-2.10.1-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.fabric.MoonlightFabric.onInitialize(MoonlightFabric.java:36) ~[moonlight-1.20-2.10.1-fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
	... 7 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.mehvahdjukaar.moonlight.api.trades.ItemListingRegistry.byNameCodec()" because "net.mehvahdjukaar.moonlight.api.trades.ItemListingRegistry.INSTANCE" is null
	at net.mehvahdjukaar.moonlight.api.trades.ModItemListing.<clinit>(ModItemListing.java:11) ~[moonlight-1.20-2.10.1-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.trades.ItemListingRegistry.<init>(ItemListingRegistry.java:46) ~[moonlight-1.20-2.10.1-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.trades.ItemListingRegistry.<clinit>(ItemListingRegistry.java:31) ~[moonlight-1.20-2.10.1-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.core.Moonlight.commonInit(Moonlight.java:71) ~[moonlight-1.20-2.10.1-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.fabric.MoonlightFabric.onInitialize(MoonlightFabric.java:36) ~[moonlight-1.20-2.10.1-fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
	... 7 more
```
