### ISSUE TITLE
[🐞1.20.1]: game crashes upon joining server 

### ISSUE THREAD

**Issue by newtitanagle** [MehVahdJukaar/Moonlight#214]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

forge_1.20-2.11.12

### Issue Detail

the game keeps crashing upon joining server with the same mod pack 

### Log Attachment

-- Head --
Thread: Render thread
Suspected Mods: 
	Supplementaries (supplementaries), Version: 1.20-2.8.10
		Issue tracker URL: https://github.com/MehVahdJukaar/Supplementaries/issues
		at TRANSFORMER/supplementaries@1.20-2.8.10/net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.checkDatapackRegistry(VibeChecker.java:58)

	Moonlight Library (moonlight), Version: 1.20-2.11.12
		Issue tracker URL: https://github.com/MehVahdJukaar/Moonlight/issues
		at TRANSFORMER/moonlight@1.20-2.11.12/net.mehvahdjukaar.moonlight.api.misc.DataObjectReference.getHolder(DataObjectReference.java:49)
Stacktrace:
	at net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.checkDatapackRegistry(VibeChecker.java:58) ~[supplementaries-1.20-2.8.10.jar%23449!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.checkVibe(VibeChecker.java:25) ~[supplementaries-1.20-2.8.10.jar%23449!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge.onServerTick(ServerEventsForge.java:228) ~[supplementaries-1.20-2.8.10.jar%23449!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.__ServerEventsForge_onServerTick_LevelTickEvent.invoke(.dynamic) ~[supplementaries-1.20-2.8.10.jar%23449!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:925) ~[forge-1.20.1-47.2.17-universal.jar%23473!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin from mod modernfix,pl:mixin:A}

### OPTIONAL: Which mods are affected?

Supplementaries

**Comment by newtitanagle** [comment]
hear is the full log 
[latest_stdout.log](https://github.com/MehVahdJukaar/Moonlight/files/15036854/latest_stdout.log)

**Comment by MehVahdJukaar** [comment]
what i see is an unrelated issue from bcc mod

 `Mixin apply for mod bcc failed bcc.mixins.json:ServerStatusPingerMixin`
