### ISSUE TITLE
[🐞]: Moonlight Lib attempts to load FluidRenderHandlerRegistry on server for soft_fluids, resulting in crash

### ISSUE THREAD

**Issue by Partonetrain** [MehVahdJukaar/Moonlight#220]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

1.20-2.11.21-fabric

### Issue Detail

While server is booting and loading data, when it gets to soft_fluids, it crashes from trying to load client code

### Log Attachment

```
>> Errors in element supplementaries:builders_tea:
java.lang.IllegalStateException: Failed to parse supplementaries:moonlight/soft_fluids/builders_tea.json from pack fabric
        at net.minecraft.class_7655.method_45122(class_7655.java:179)
        at net.minecraft.class_7655$class_7657.method_45132(class_7655.java:61)
        at net.minecraft.class_7655.method_45120(class_7655.java:98)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at net.minecraft.class_7655.method_45121(class_7655.java:98)
        at net.minecraft.class_7237.method_45142(class_7237.java:67)
        at net.minecraft.class_7237.method_45143(class_7237.java:71)
        at net.minecraft.class_7237.method_42098(class_7237.java:34)
        at net.minecraft.server.Main.method_43612(Main.java:162)
        at net.minecraft.class_156.method_43498(class_156.java:944)
        at net.minecraft.class_156.method_43499(class_156.java:938)
        at net.minecraft.server.Main.main(Main.java:160)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandlerRegistry in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at net.mehvahdjukaar.moonlight.api.fluids.fabric.SoftFluidImpl.getRenderingData(SoftFluidImpl.java:19)
        at net.mehvahdjukaar.moonlight.api.fluids.SoftFluid.getRenderingData(SoftFluid.java)
        at net.mehvahdjukaar.moonlight.api.fluids.SoftFluid.<init>(SoftFluid.java:77)
        at net.mehvahdjukaar.moonlight.api.fluids.SoftFluid$Builder.build(SoftFluid.java:528)
        at net.mehvahdjukaar.moonlight.api.fluids.SoftFluid.create(SoftFluid.java:607)
        at com.mojang.datafixers.util.Function12.lambda$curry6$10(Function12.java:30)
        at com.mojang.datafixers.util.Function6.lambda$curry3$4(Function6.java:18)
        at com.mojang.serialization.DataResult$Instance.ap3(DataResult.java:340)
        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:321)
        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107)
        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$1(MapDecoder.java:52)
        at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139)
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:137)
        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
        at com.mojang.serialization.Decoder.parse(Decoder.java:18)
        at net.minecraft.class_7655.method_45122(class_7655.java:175)
        ... 16 more
```
(many near-identical errors)

### OPTIONAL: Which mods are affected?

Supplementaries, and mod that adds soft_fluids

**Comment by MehVahdJukaar** [comment]
i believe this was fixed
