### ISSUE TITLE
[🐞]: Crash when interacting with FTB Teams Change Gamemode Button | xaeroworldmap Interaction?

### ISSUE THREAD

**Issue by James-Webb554** [MehVahdJukaar/Moonlight#222]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

moonlight-1.20-2.11.31-forge.jar

### Issue Detail

Modpack Industrial Village 1.5

1) Login, get opped
2) Open Inv, click change gamemode button from FTB Teams
3) Crash to desktop

### Log Attachment

<details>
<summary> Partially Crash Report </summary>
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-06-09 20:04:28
Description: Rendering screen

java.lang.NullPointerException: Rendering screen

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:968) ~[client-1.20.1-20230612.114412-srg.jar%23656!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin,pl:mixin:APP:vinery-common.mixins.json:GameRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:sleep_tight-common.mixins.json:GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:fruitfulfun.mixins.json:client.GameRendererMixin,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:APP:brewery-common.mixins.json:GameRendererMixin,pl:mixin:APP:controllable.common.mixins.json:client.GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeGameRendererMixin,pl:mixin:APP:mixins.artifacts.common.json:item.wearable.nightvisiongoggles.client.GameRendererMixin,pl:mixin:APP:armourersworkshop-compatibility-mixins.json:GameRendererMixin,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer,pl:mixin:APP:lychee.mixins.json:GameRendererAccess,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
-- Screen render details --
Details:
Screen name: net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen
Mouse location: Scaled: (358, 172). Absolute: (1074.000000, 517.000000)
Screen size: Scaled: (640, 339). Absolute: (1920, 1017). Scale factor of 3.000000
Stacktrace:
at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:968) ~[client-1.20.1-20230612.114412-srg.jar%23656!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin,pl:mixin:APP:vinery-common.mixins.json:GameRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:sleep_tight-common.mixins.json:GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:fruitfulfun.mixins.json:client.GameRendererMixin,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:APP:brewery-common.mixins.json:GameRendererMixin,pl:mixin:APP:controllable.common.mixins.json:client.GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeGameRendererMixin,pl:mixin:APP:mixins.artifacts.common.json:item.wearable.nightvisiongoggles.client.GameRendererMixin,pl:mixin:APP:armourersworkshop-compatibility-mixins.json:GameRendererMixin,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer,pl:mixin:APP:lychee.mixins.json:GameRendererAccess,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23656!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:mffs:resizeDisplayHook,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:mffs:resizeDisplayHook,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23656!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:mffs:resizeDisplayHook,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:mffs:resizeDisplayHook,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.14.jar:?] {re:classloading,pl:runtimedistcleaner:A}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.14.jar:?] {}
at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.14.jar:?] {}
at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.14.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Affected level --
Details:
All players: 1 total; [LocalPlayer['_Zerys'/333, l='ClientLevel', x=-187.88, y=76.00, z=14.63]]
Chunk stats: 352, 352
Level dimension: minecraft:overworld
Level spawn location: World: (-188,76,19), Section: (at 4,12,3 in -12,4,1; chunk contains blocks -192,-64,16 to -177,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
Level time: 74008 game time, 84192 day time
Server brand: forge
Server type: Non-integrated multiplayer server

-- Last reload --
Details:
Reload number: 1
Reload reason: initial
Finished: Yes
Packs: Workshop - auto-generated client assets, vanilla, mod_resources, KubeJS Resource Pack [assets], VanillaTweaks_r482322.zip, iv-rp, Advanced_Generators_Redux.zip, file/LootrChestRetexture_v1.1_1.19.zip, Moonlight Mods Dynamic Assets, file/Tool_Belt_Retextured_1.20.x.zip, file/Lopy-Create-Sophisticated-Backpacks.zip, file/v2_REFRESH_Building_Gadgets_Create_Like.zip

-- System Details --
Details:
Minecraft Version: 1.20.1
Minecraft Version ID: 1.20.1
Operating System: Windows 10 (amd64) version 10.0
Java Version: 17.0.8, Microsoft
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
Memory: 1013876224 bytes (966 MiB) / 8220835840 bytes (7840 MiB) up to 9495904256 bytes (9056 MiB)
CPUs: 24
Processor Vendor: AuthenticAMD
Processor Name: AMD Ryzen 9 3900X 12-Core Processor            
Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
Microarchitecture: Zen 2
Frequency (GHz): 3.80
Number of physical packages: 1
Number of physical CPUs: 12
Number of logical CPUs: 24
Graphics card #0 name: NVIDIA GeForce RTX 2080 SUPER
Graphics card #0 vendor: NVIDIA (0x10de)
Graphics card #0 VRAM (MB): 4095.00
Graphics card #0 deviceId: 0x1e81
Graphics card #0 versionInfo: DriverVersion=32.0.15.5599
Memory slot #0 capacity (MB): 16384.00
Memory slot #0 clockSpeed (GHz): 2.67
Memory slot #0 type: DDR4
Memory slot #1 capacity (MB): 16384.00
Memory slot #1 clockSpeed (GHz): 2.67
Memory slot #1 type: DDR4
Virtual memory max (MB): 44462.57
Virtual memory used (MB): 37763.29
Swap memory total (MB): 11776.00
Swap memory used (MB): 860.90
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9056m -Xms256m
Loaded Shaderpack: (off)
Launched Version: forge-47.2.14
Backend library: LWJGL version 3.3.1 build 7
Backend API: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 555.99, NVIDIA Corporation
Window size: 1920x1017
GL Caps: Using framebuffer using OpenGL 3.2... (8 KB left)

</details>

### OPTIONAL: To Produce

1) Login, get opped
2) Open Inv, click change gamemode button from FTB Teams
3) Crash to desktop

### OPTIONAL: Which mods are affected?

- Interactions mention xaeroworldmap

**Comment by MehVahdJukaar** [comment]
I need the whole latest.log
