### ISSUE TITLE
[🐞]: we try to play "Industrial Village" with some extra mods. Enter the server world but it crash after join.

### ISSUE THREAD

**Issue by kami2j** [MehVahdJukaar/Moonlight#235]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

moonlight-1.20-2.12.6

### Issue Detail

here is the problem i think:
-- Head --
Thread: Render thread
Suspected Mods: 
	Moonlight Library (moonlight), Version: 1.20-2.12.6
		Issue tracker URL: https://github.com/MehVahdJukaar/Moonlight/issues
		at TRANSFORMER/moonlight@1.20-2.12.6/net.mehvahdjukaar.moonlight.api.misc.DataObjectReference.getHolder(DataObjectReference.java:50)

	Supplementaries (supplementaries), Version: 1.20-2.8.17
		Issue tracker URL: https://github.com/MehVahdJukaar/Supplementaries/issues
		at TRANSFORMER/supplementaries@1.20-2.8.17/net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.checkDatapackRegistry(VibeChecker.java:60)
Stacktrace:
	at net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.checkDatapackRegistry(VibeChecker.java:60) ~[supplementaries-1.20-2.8.17.jar%23683!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.checkVibe(VibeChecker.java:27) ~[supplementaries-1.20-2.8.17.jar%23683!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge.onServerTick(ServerEventsForge.java:228) ~[supplementaries-1.20-2.8.17.jar%23683!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.__ServerEventsForge_onServerTick_LevelTickEvent.invoke(.dynamic) ~[supplementaries-1.20-2.8.17.jar%23683!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:925) ~[forge-1.20.1-47.3.1-universal.jar%23729!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin,pl:mixin:A}
-- Affected level --

### Log Attachment

[crash-report.txt](https://github.com/user-attachments/files/16118137/crash-report.txt)

**Comment by MehVahdJukaar** [comment]
Some mod is breaking dayapack registries of this mod (and all other mods for that matter). You have to find which
