### ISSUE TITLE
[🐞]:  Level must be either ServerLevel or ClientLevel

### ISSUE THREAD

**Issue by Skullians** [MehVahdJukaar/Moonlight#247]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.19.2-fabric

### Moonlight Lib Version

moonlight 1.19.2 2.3.6

### Issue Detail

I've seen this happen a couple times.
We use neruina to fix ticking entities / players and whatnot, and we frequently get a notification from neruina relating to the FakePlayerManager of Moonlight.

### Log Attachment

<details>
<summary>latest.log</summary>

java.lang.IllegalArgumentException: Level must be either ServerLevel or ClientLevel
    at net.mehvahdjukaar.moonlight.api.util.fake_player.FakePlayerManager.get(FakePlayerManager.java:34)
    at net.mehvahdjukaar.moonlight.api.util.fake_player.FakePlayerManager.get(FakePlayerManager.java:41)
    at net.mehvahdjukaar.moonlight.api.util.fake_player.FakePlayerManager.getDefault(FakePlayerManager.java:56)
    at net.mehvahdjukaar.supplementaries.common.entities.SlingshotProjectileEntity.method_24920(SlingshotProjectileEntity.java:170)
    at net.minecraft.class_1676.method_7488(class_1676.java:153)
    at net.mehvahdjukaar.moonlight.api.entity.ImprovedProjectileEntity.method_5773(ImprovedProjectileEntity.java:219)
    at net.mehvahdjukaar.supplementaries.common.entities.SlingshotProjectileEntity.method_5773(SlingshotProjectileEntity.java:201)
    at net.minecraft.class_3218.method_18762(class_3218.java:712)
    at net.minecraft.class_1937.mixinextras$bridge$accept$207(class_1937.java)
    at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
    at net.minecraft.class_1937.wrapOperation$epg000$neruina$catchTickingEntities$notTheCauseOfTickLag(class_1937.java:14067)
    at net.minecraft.class_1937.method_18472(class_1937.java:466)
    at net.minecraft.class_3218.method_31420(class_3218.java:371)
    at net.minecraft.class_5574.method_31791(class_5574.java:54)
    at net.minecraft.class_3218.method_18765(class_3218.java:339)
    at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
    at net.minecraft.class_3176.method_3813(class_3176.java:289)
    at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
    at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)

</details>

### OPTIONAL: To Produce

1) Download supplementaries and moonlight api
2) see the error ocassionally. not been able to always reproduce it.

### OPTIONAL: Which mods are affected?

supplementaries
not entirely sure

**Comment by Skullians** [comment]
I have just found https://github.com/MehVahdJukaar/Supplementaries/issues/515 but we don't use TabTPS.

**Comment by MehVahdJukaar** [comment]
Happens when a slingshot projectile is fired. It's somehow getting passes a non vanilla level somehow. Would be useful finding the mod that allows this to happen as doesn't on its own

**Comment by Skullians** [comment]
Oh man.
I'll look into it if I have the time but we have over 250 mods

**Comment by tr1kright** [comment]
Can I help you with that? I'm having the same issue on FORGE 1.20.1 with FakeLevelMenager. I have a spark profile where I created a new world and just ran around for a while.

**Comment by MehVahdJukaar** [comment]
uhm forgot this existed. send log pls

**Comment by MehVahdJukaar** [comment]
actually that cant be. you say 1.20.1 but i dont see the log line that this issue is reporting appearing anywhere in 1.20 version

**Comment by tr1kright** [comment]
uh, yeah, https://spark.lucko.me/W9RGFVQEvZ

**Comment by tr1kright** [comment]
sry :)

**Comment by tr1kright** [comment]
Maybe it's because of the other mod's features. I don't know much about profiling and coding, to be honest

**Comment by MehVahdJukaar** [comment]
ok this issue here is a crash report. you sent me a spark report. send your crash report or open a new issue if its a different one

**Comment by tr1kright** [comment]
This is different, I'll open an issue

**Comment by MehVahdJukaar** [comment]
and take the spark report AFTER the server has started

**Comment by tr1kright** [comment]
Sorry for the confusion, for some reason I thought there was the same performance issue as me.

I tried disabling and enabling Embeddium when creating the report and now FakePlayerManager won't load at all. That's weird, but it's getting late, so I'll continue tomorrow in my report. Once again, I'm sorry about that.
