### ISSUE TITLE
[🐞]: server startup error, related to "fake_player.FPClientAccess"

### ISSUE THREAD

**Issue by Mitchell5200** [MehVahdJukaar/Moonlight#272]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

moonlight-1.20-2.13.25

### Issue Detail

Loaded a new 1.20.1, Forge 47.3.11 server with moonlight 2.13.25 included in the mods list, the below error gets printed, and the server process gets locked up

> [10Nov2024 23:19:59.618] [main/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: 'net.minecraft.world.entity.player.Player net.mehvahdjukaar.moonlight.core.fake_player.FPClientAccess.get(net.minecraft.world.level.Level, com.mojang.authlib.GameProfile)'

### Log Attachment

[2024-11-10-1.log](https://github.com/user-attachments/files/17692031/2024-11-10-1.log)

<details>
<summary>ERROR#0</summary>

`java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.Player net.mehvahdjukaar.moonlight.core.fake_player.FPClientAccess.get(net.minecraft.world.level.Level, com.mojang.authlib.GameProfile)'
at TRANSFORMER/moonlight@1.20-2.13.25/net.mehvahdjukaar.moonlight.api.util.FakePlayerManager.get(FakePlayerManager.java:34)
at TRANSFORMER/moonlight@1.20-2.13.25/net.mehvahdjukaar.moonlight.api.util.FakePlayerManager.getDefault(FakePlayerManager.java:54)
at TRANSFORMER/supplementaries@1.20-3.1.1/net.mehvahdjukaar.supplementaries.common.block.faucet.FaucetBehaviorsManager.parse(FaucetBehaviorsManager.java:102)
at TRANSFORMER/moonlight@1.20-2.13.25/net.mehvahdjukaar.moonlight.api.misc.RegistryAccessJsonReloadListener.runReloads(RegistryAccessJsonReloadListener.java:28)
at TRANSFORMER/moonlight@1.20-2.13.25/net.mehvahdjukaar.moonlight.core.Moonlight.afterDataReload(Moonlight.java:125)
at TRANSFORMER/moonlight@1.20-2.13.25/net.mehvahdjukaar.moonlight.forge.MoonlightForge.onTagUpdated(MoonlightForge.java:72)
at TRANSFORMER/moonlight@1.20-2.13.25/net.mehvahdjukaar.moonlight.forge.__MoonlightForge_onTagUpdated_TagsUpdatedEvent.invoke(.dynamic)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.ReloadableServerResources.m_206868_(ReloadableServerResources.java:90)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader.m_244809_(WorldLoader.java:44)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214652_(Util.java:783)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214679_(Util.java:772)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:166)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.11/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.11/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.11/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)`

</details>

	
And

<details>
<summary>ERROR#1</summary>

`[10Nov2024 23:19:59.621] [main/WARN] [net.minecraft.server.Main/]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.Player net.mehvahdjukaar.moonlight.core.fake_player.FPClientAccess.get(net.minecraft.world.level.Level, com.mojang.authlib.GameProfile)'
`

</details>

**Comment by MehVahdJukaar** [comment]
this on a server?

**Comment by MehVahdJukaar** [comment]
use newest supplementaries

**Comment by suerion** [comment]
@MehVahdJukaar 

```
[17:14:59] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'supplementaries' at 'net.mehvahdjukaar.supplementaries.fabric.SupplementariesFabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/mehvahdjukaar/moonlight/api/misc/FakeLevel
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:91) ~[supplementaries-1.21-3.0.11-alpha-fabric.jar:?]
        at knot/net.mehvahdjukaar.supplementaries.fabric.SupplementariesFabric.onInitialize(SupplementariesFabric.java:25) ~[supplementaries-1.21-3.0.11-alpha-fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.mehvahdjukaar.moonlight.api.misc.FakeLevel
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:91) ~[supplementaries-1.21-3.0.11-alpha-fabric.jar:?]
        at knot/net.mehvahdjukaar.supplementaries.fabric.SupplementariesFabric.onInitialize(SupplementariesFabric.java:25) ~[supplementaries-1.21-3.0.11-alpha-fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
```

**Comment by suerion** [comment]
- moonlight 1.21-2.15.15
- supplementaries 1.21-3.0.10-alpha

On server Fabric -> think the first issue is fixed, (same on forge) but yet this error above happens

**Comment by skullysmods** [comment]
Same problem on my Fabric server with :

- moonlight-1.20-2.13.25
- supplementaries-1.20-3.1.3

Log :
[latest.log](https://github.com/user-attachments/files/17693055/latest.log)

**Comment by suerion** [comment]
The server starts now again without issues from moonlight, will keep an eye on this issue.
I'm using 1.21-2.16.3

**Comment by suerion** [comment]
Had no issues with fake

**Comment by MehVahdJukaar** [comment]
does this still happen?

**Comment by suerion** [comment]
@MehVahdJukaar on my side, i had only the issue with the textures, 

This issue is fixed on my side

**Comment by MehVahdJukaar** [comment]
Nice
