### ISSUE TITLE
[Bug] Failed to process update information

### ISSUE THREAD

**Issue by ErythroCraft** [MehVahdJukaar/Moonlight#55]
[07Nov.2022 10:09:19.981] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [moonlight] Starting version check at https://raw.githubusercontent.com/MehVahdJukaar/Moonlight/master/forge/update.json
[07Nov.2022 10:09:20.314] [Forge Version Check/WARN] [net.minecraftforge.fml.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar%23121!/:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:183) ~[fmlcore-1.19.2-43.1.47.jar%23185!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) [fmlcore-1.19.2-43.1.47.jar%23185!/:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%23121!/:?]
	... 6 more

**Comment by MehVahdJukaar** [comment]
We're you online here?

**Comment by ErythroCraft** [comment]
I don't know. Are you online here?

**Comment by MehVahdJukaar** [comment]
I meant to say if you were online when that happen as it's a problem with forge version checker which is supposed to access the web to check what the newest version is

**Comment by ErythroCraft** [comment]
yes- I got an oficial IP.

**Comment by ErythroCraft** [comment]
Maybe you need more Informations?
