### ISSUE TITLE
Newest 1.19.2 Version Preventing Dedicated Server from Stopping

### ISSUE THREAD

**Issue by EvionFox** [MehVahdJukaar/Moonlight#77]
Server is running Fabric 1.19.2
I just updated to Moonlight 1.19.2-2.1.28

Upon attempting to stop the server, I am getting this message in the logs:

[22:58:13] [Server thread/ERROR]: Exception stopping the server
java.lang.NoClassDefFoundError: net/minecraft/class_742
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.mehvahdjukaar.moonlight.fabric.MoonlightFabric.lambda$onInitialize$4(MoonlightFabric.java:32) ~[moonlight-1.19.2-2.1.28-fabric.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents.lambda$static$2(ServerWorldEvents.java:46) ~[fabric-lifecycle-events-v1-2.2.3+1b46dc7890-4dbc38027e346cac.jar:?]
        at net.minecraft.server.MinecraftServer.handler$egc000$onUnloadWorldAtShutdown(MinecraftServer.java:12836) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:596) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:547) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_742
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 16 more

Full Latest log here: https://pastebin.com/GkN7eZZG

**Comment by MehVahdJukaar** [comment]
Did you try new version?

**Comment by EvionFox** [comment]
Sorry, I should have been clearer with the report. This error is with the 2.1.28 version that was just released. I had to roll back to 2.1.27 to fix the error. I don't see any version on Curseforge that is newer than 2.1.28.

**Comment by EvionFox** [comment]
I saw the 2.1.30 version was available on Curseforge. I switched the server to that version, booted it up successfully and also successfully shut it down. It solved the "Exception stopping the server" error. Thank you for your hard work!

**Comment by MehVahdJukaar** [comment]
Nice it worked. Cool no problem!
